---

- src: https://github.com/OULibraries/ansible-role-centos7
  version: master
  name: OULibraries.centos7

- src: https://github.com/OULibraries/ansible-role-mariadb
  name: OULibraries.mariadb
  version: master       

- src: https://github.com/OULibraries/ansible-role-d7
  name: OULibraries.d7
  version: origin/dev-removedb

- src: https://github.com/OULibraries/ansible-role-ngrok
  version: master
  name: OULibraries.ngrok
