---
- hosts: default
  sudo: yes
  vars_files:
    - my-vars.yml
  pre_tasks:
    - name: /srv is a directory
      file: path=/srv state=directory mode=0755 force=yes
  roles:
    - jsnshrmn.centos7
    - jsnshrmn.d7
    - jsnshrmn.ngrok
  tasks:
    - name: Disable selinux for vagrant
      selinux: state=disabled
    - name: Add apache user to vagrant group
      command: usermod -a -G vagrant apache
  post_tasks:
    - name: getting apache uid
      command: id -u apache
      register: apache_user
    - name: getting apache gid
      command: id -g apache
      register: apache_group
    - name: Unmount /srv
      mount: name=/srv fstype=vboxsf src=srv  state=unmounted
    - name: Mount srv to /srv with the right permissions
      mount:
        name: /srv
        fstype: vboxsf
        src: srv
        opts: "uid={{apache_user.stdout}},gid={{apache_group.stdout}}"
        state: mounted
